# Generated by Django 2.2.4 on 2019-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20190812_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='isadmin',
            field=models.IntegerField(default=0),
        ),
    ]
