# Generated by Django 2.2.4 on 2019-10-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
